export const dom = {
    coinsSpan: document.getElementById('coins'),
    bitcoinsSpan: document.getElementById('bitcoins'),
    rankSpan: document.getElementById('rank'),
    passiveDisplay: document.getElementById('passive-display'),
    bsodOverlay: document.getElementById('bsod-overlay'),
    laptopContainer: document.getElementById('laptop-container'),
    laptopScreen: document.getElementById('laptop-screen'),
    monitorArea: document.getElementById('monitor-area'),
    monitorBody: document.getElementById('monitor'),
    mouseDevice: document.getElementById('mouse-device'),
    cablePopup: document.getElementById('cable-popup'),
    finalScreen: document.getElementById('final-screen'),
    finalTimeSpan: document.getElementById('final-time'),
    matrixCanvas: document.getElementById('matrix-canvas'),
    adTimerDiv: document.getElementById('ad-timer'),
    adCountdownSpan: document.getElementById('ad-countdown'),
    farmButtonsDiv: document.getElementById('farm-buttons'),
    questsListDiv: document.getElementById('quests-list'),
    pcPartsDiv: document.getElementById('pc-parts'),
    pcCase: document.getElementById('pc-case'),
    pcMonitorArea: document.getElementById('pc-monitor-area'),
    buyRackBtn: document.getElementById('buy-rack'),
    racksContainer: document.getElementById('racks-container'),
    // Кнопки магазина
    buyMouse: document.getElementById('buy-mouse'),
    buyMonitor: document.getElementById('buy-monitor'),
    buyLaptop: document.getElementById('buy-laptop'),
    buyWallpaper: document.getElementById('buy-wallpaper'),
    buyFinal: document.getElementById('buy-final'),
    fixCableCoins: document.getElementById('fix-cable-coins'),
    fixCableAd: document.getElementById('fix-cable-ad'),
    donateBtn: document.getElementById('donate-btn'),
    // Новые индикаторы
    clickPowerDisplay: document.getElementById('click-power-display'),
    passiveDisplaySmall: document.getElementById('passive-display-small'),
};